# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-23 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spu',
            name='sales',
            field=models.IntegerField(verbose_name='销量'),
        ),
    ]
